DROP TABLE IF EXISTS Partie ;
CREATE TABLE Partie (IdP_Partie INT(20) AUTO_INCREMENT NOT NULL,
DateDebutP_Partie DATETIME,
DateFinP_DatePartieF DATETIME,
IdGagnante_Partie INT(20),
IdJC_JeuCarte **NOT FOUND**(20),
IdJIA_JIA **NOT FOUND**(20),
IdJH_JHumaine **NOT FOUND**(20),
PRIMARY KEY (IdP_Partie)) ENGINE=InnoDB;

DROP TABLE IF EXISTS Joueuse ;
CREATE TABLE Joueuse (IdJ_Joueuse INT(20) AUTO_INCREMENT NOT NULL,
DateCreaJ_Joueuse DATETIME,
CouleurJ_Joueuse VARCHAR2(100),
PRIMARY KEY (IdJ_Joueuse)) ENGINE=InnoDB;

DROP TABLE IF EXISTS Manche ;
CREATE TABLE Manche (IdM_Manche INT(20) AUTO_INCREMENT NOT NULL,
ScoreJ1_Partie INT(20),
ScoreJ2_Partie INT(20),
DateDebutM_Manche DATETIME,
DateFinM_Manche DATETIME,
IdGagnanteM_Manche INT(20),
IdP_Partie **NOT FOUND**(20),
IdJH_JHumaine **NOT FOUND**(20),
IdJIA_JIA **NOT FOUND**(20),
PRIMARY KEY (IdM_Manche)) ENGINE=InnoDB;

DROP TABLE IF EXISTS Tour ;
CREATE TABLE Tour (IdT_Tour INT(20) AUTO_INCREMENT NOT NULL,
ScoreCourantJ1_Tour INT(20),
ScoreCourantJ2_Tour INT(20),
CogneJ1_Tour BOOL,
CogneJ2_Tour BOOL,
PilePiocheJ1_Tour VARCHAR2(100),
PilePiocheJ2_Tour VARCHAR2(100),
CartePiocheJ1_Tour VARCHAR2(200),
CartePiocheJ2_Tour VARCHAR2(200),
CarteDefausseJ1_Tour VARCHAR2(200),
CarteDefausseJ2_Tour VARCHAR2(200),
IdM_Manche **NOT FOUND**(20),
IdJIA_JIA **NOT FOUND**(20),
IdJH_JHumaine **NOT FOUND**(20),
PRIMARY KEY (IdT_Tour)) ENGINE=InnoDB;

DROP TABLE IF EXISTS JeuCarte ;
CREATE TABLE JeuCarte (IdJC_JeuCarte INT(20) AUTO_INCREMENT NOT NULL,
LabelJC_JeuCarte VARCHAR2(100),
UrlJC_JeuCarte VARCHAR2(300),
PRIMARY KEY (IdJC_JeuCarte)) ENGINE=InnoDB;

DROP TABLE IF EXISTS Carte ;
CREATE TABLE Carte (CodeC_Carte VARCHAR2(10) AUTO_INCREMENT NOT NULL,
LabelC_Carte VARCHAR2(20),
ValeurC_Carte INT(2),
CouleurC_Carte VARCHAR2(100),
ImageC_Carte MEDIUMBLOB,
IdJC_JeuCarte **NOT FOUND**(10),
PRIMARY KEY (CodeC_Carte)) ENGINE=InnoDB;

DROP TABLE IF EXISTS JHumaine ;
CREATE TABLE JHumaine (IdJH_JHumaine INT(20) AUTO_INCREMENT NOT NULL,
NomJH_JHumaine VARCHAR2(100),
PrenomJH_JHumaine VARCHAR2(100),
IdJ_Joueuse **NOT FOUND**(20),
PRIMARY KEY (IdJH_JHumaine)) ENGINE=InnoDB;

DROP TABLE IF EXISTS JIA ;
CREATE TABLE JIA (IdJIA_JIA INT(20) AUTO_INCREMENT NOT NULL,
NomIA_JIA VARCHAR2(100),
IdJ_Joueuse **NOT FOUND**(20),
PRIMARY KEY (IdJIA_JIA)) ENGINE=InnoDB;

DROP TABLE IF EXISTS Configuration ;
CREATE TABLE Configuration (IdConf_Configuration INT(20) AUTO_INCREMENT NOT NULL,
PRIMARY KEY (IdConf_Configuration)) ENGINE=InnoDB;

DROP TABLE IF EXISTS Date ;
CREATE TABLE Date (DateConf_Date DATETIME AUTO_INCREMENT NOT NULL,
PRIMARY KEY (DateConf_Date)) ENGINE=InnoDB;

DROP TABLE IF EXISTS LGN_ConfIA ;
CREATE TABLE LGN_ConfIA (IdJIA_JIA **NOT FOUND**(20) AUTO_INCREMENT NOT NULL,
IdConf_Configuration **NOT FOUND**(20) NOT NULL,
DateConf_Date **NOT FOUND**(20) NOT NULL,
ValIA_LGN_ConfIA INT(20),
PRIMARY KEY (IdJIA_JIA,
 IdConf_Configuration,
 DateConf_Date)) ENGINE=InnoDB;

ALTER TABLE Partie ADD CONSTRAINT FK_Partie_IdJC_JeuCarte FOREIGN KEY (IdJC_JeuCarte) REFERENCES JeuCarte (IdJC_JeuCarte);

ALTER TABLE Partie ADD CONSTRAINT FK_Partie_IdJIA_JIA FOREIGN KEY (IdJIA_JIA) REFERENCES JIA (IdJIA_JIA);
ALTER TABLE Partie ADD CONSTRAINT FK_Partie_IdJH_JHumaine FOREIGN KEY (IdJH_JHumaine) REFERENCES JHumaine (IdJH_JHumaine);
ALTER TABLE Manche ADD CONSTRAINT FK_Manche_IdP_Partie FOREIGN KEY (IdP_Partie) REFERENCES Partie (IdP_Partie);
ALTER TABLE Manche ADD CONSTRAINT FK_Manche_IdJH_JHumaine FOREIGN KEY (IdJH_JHumaine) REFERENCES JHumaine (IdJH_JHumaine);
ALTER TABLE Manche ADD CONSTRAINT FK_Manche_IdJIA_JIA FOREIGN KEY (IdJIA_JIA) REFERENCES JIA (IdJIA_JIA);
ALTER TABLE Tour ADD CONSTRAINT FK_Tour_IdM_Manche FOREIGN KEY (IdM_Manche) REFERENCES Manche (IdM_Manche);
ALTER TABLE Tour ADD CONSTRAINT FK_Tour_IdJIA_JIA FOREIGN KEY (IdJIA_JIA) REFERENCES JIA (IdJIA_JIA);
ALTER TABLE Tour ADD CONSTRAINT FK_Tour_IdJH_JHumaine FOREIGN KEY (IdJH_JHumaine) REFERENCES JHumaine (IdJH_JHumaine);
ALTER TABLE Carte ADD CONSTRAINT FK_Carte_IdJC_JeuCarte FOREIGN KEY (IdJC_JeuCarte) REFERENCES JeuCarte (IdJC_JeuCarte);
ALTER TABLE JHumaine ADD CONSTRAINT FK_JHumaine_IdJ_Joueuse FOREIGN KEY (IdJ_Joueuse) REFERENCES Joueuse (IdJ_Joueuse);
ALTER TABLE JIA ADD CONSTRAINT FK_JIA_IdJ_Joueuse FOREIGN KEY (IdJ_Joueuse) REFERENCES Joueuse (IdJ_Joueuse);
ALTER TABLE LGN_ConfIA ADD CONSTRAINT FK_LGN_ConfIA_IdJIA_JIA FOREIGN KEY (IdJIA_JIA) REFERENCES JIA (IdJIA_JIA);
ALTER TABLE LGN_ConfIA ADD CONSTRAINT FK_LGN_ConfIA_IdConf_Configuration FOREIGN KEY (IdConf_Configuration) REFERENCES Configuration (IdConf_Configuration);
ALTER TABLE LGN_ConfIA ADD CONSTRAINT FK_LGN_ConfIA_DateConf_Date FOREIGN KEY (DateConf_Date) REFERENCES Date (DateConf_Date);
